apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-qa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restaurant-qa
  template:
    metadata:
      labels:
        app: restaurant-qa
    spec:
      containers:
      - name: restaurant-qa
        image: restaurant-qa:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "1"
            memory: "4Gi"
          requests:
            cpu: "0.5"
            memory: "2Gi"
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: chroma
          mountPath: /app/chroma_db
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-pvc
      - name: chroma
        persistentVolumeClaim:
          claimName: chroma-pvc